# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4515bff40fa0e3a1556b0b552d74c8860194d6c4ce1210799ac63f05abf3df8f5c8edcbefe5875e1cb9522e7310febfcaccc95c1c4efd476d5ea3dbf16c5ce6b

test:
  secret_key_base: 38436c857613103aff41b7adad4f55df3864961db9db46d915dc2113627fbc89a548eb0b248e3c0c918f55ab34ce0e8ae98234588268a725647e6099bccd0678

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
